parameters:
  artifactName: 'packages'
  targetPath: 'dist/packages'

steps:
- task: PublishPipelineArtifact@0
  inputs:
    ${{ if parameters.artifactName }}:
      artifactName: ${{ parameters.artifactName }}
    ${{ if eq(parameters.artifactName, '') }}:
      artifactName: $(packageName)
    ${{ if parameters.targetPath }}:
      targetPath: ${{ parameters.targetPath }}
    ${{ if eq(parameters.targetPath, '') }}:
      targetPath: dist/packages/$(packageName)
  displayName: Publish build artifacts
