steps:
- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'npmrc'
    targetPath: '.npmrc'
  condition: and(succeeded(), contains(variables['Build.SourceBranch'], 'refs/tags/'))
  displayName: Publish .npmrc
