parameters:
  summaryFileLocation: 'coverage/${{Build.Repository.Name}}/cobertura-coverage.xml'
  reportDirectory: 'coverage/${{Build.Repository.Name}}'

steps:
- task: PublishCodeCoverageResults@1
  condition: succeededOrFailed()
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: ${{ parameters.summaryFileLocation }}
    reportDirectory: ${{ parameters.reportDirectory }}
    failIfCoverageEmpty: true
  displayName: Publish code coverage results - ${{ parameters.reportDirectory }}
