steps:
- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunTitle: ${{ parameters.testRunTitle }}
    searchFolder: ${{ parameters.searchFolder }}
    testResultsFormat: JUnit
    testResultsFiles: "**/TESTS*.xml"
  displayName: Publish ${{ parameters.testRunTitle }} test results
