parameters:
  testRunTitle: ''
  searchFolder: ''

steps:
- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    ${{ if parameters.testRunTitle }}:
      testRunTitle: ${{ parameters.testRunTitle }}
    ${{ if eq(parameters.testRunTitle, '') }}:
      testRunTitle: $(packageName)
    ${{ if parameters.searchFolder }}:
      searchFolder: ${{ parameters.searchFolder }}
    ${{ if eq(parameters.searchFolder, '') }}:
      searchFolder: $(System.DefaultWorkingDirectory)/dist/junit/$(packageName)
    testResultsFormat: JUnit
    testResultsFiles: "**/TESTS*.xml"
  displayName: Publish test results
