parameters:
  testRunTitle: 'junit'
  searchFolder: 'dist/junit/$[Build.Repository.Name]'

steps:
- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    searchFolder: $(System.DefaultWorkingDirectory)/${{ parameters.searchFolder }}
    testRunTitle: ${{ parameters.testRunTitle }}
    testResultsFormat: JUnit
    testResultsFiles: "**/TESTS*.xml"
  displayName: Publish ${{ parameters.testRunTitle }} test results
