parameters:
  name: 'default'
  dependsOn: ''
  vmImage: 'ubuntu-16.04'
  runLint: 'true'
  preBuild: []
  postBuild: []
  preTest: []
  postTest: []
  publishBuildArtifacts: []
  publishTestArtifacts: []
  publishCodeCoverageArtifacts: []
  publishReleaseNotes: 'true'
  maxParallel: 0
  matrix:
    node-10.15.3:
      nodeVersion: '10.15.3'
  additionalVariables: {}

jobs:
  - job: ${{ parameters.name }}
    variables:
      ${{ insert }}: ${{ parameters.additionalVariables }}
    dependsOn:
      - ${{ if parameters.dependsOn }}:
        - ${{ parameters.dependsOn }}
    strategy:
      maxParallel: ${{ parameters.maxParallel }}
      matrix: ${{ parameters.matrix }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    steps:
      - task: UseNode@1
        inputs:
          version: $(nodeVersion)
        displayName: Use Node $(nodeVersion)
      - template: steps/install-deps.yml
      - template: steps/build.yml
        parameters:
          preBuild: ${{ parameters.preBuild }}
          postBuild: ${{ parameters.postBuild }}
      - template: steps/test.yml
        parameters:
          preTest: ${{ parameters.preTest }}
          postTest: ${{ parameters.postTest }}

      - ${{ if eq(parameters.runLint, 'true') }}:
        - template: steps/lint.yml


      - ${{ each publishCodeCoverageArtifact in parameters.publishCodeCoverageArtifacts }}:
        - template: steps/publish-code-coverage-results.yml
          parameters:
            summaryFileLocation: ${{ publishCodeCoverageArtifact.summaryFileLocation }}
            reportDirectory: ${{ publishCodeCoverageArtifact.reportDirectory }}

      - ${{ each publishTestArtifact in parameters.publishTestArtifacts }}:
        - template: steps/publish-test-results.yml
          parameters:
            testRunTitle: ${{ publishTestArtifact.testRunTitle }}
            searchFolder: ${{ publishTestArtifact.searchFolder }}

      - ${{ each publishBuildArtifact in parameters.publishBuildArtifacts }}:
        - template: steps/publish-build-results.yml
          parameters:
            artifactName: ${{ publishBuildArtifact.artifactName }}
            targetPath: ${{ publishBuildArtifact.targetPath }}

      - ${{ if and(eq(parameters.publishReleaseNotes, 'true'), contains(variables['Build.SourceBranch'], 'refs/tags/')) }}:
        - template: steps/publish-release-notes.yml
