parameters:
  name: 'default'
  dependsOn: ''
  vmImage: 'ubuntu-16.04'
  runLint: 'true'
  preBuild: []
  postBuild: []
  preTest: []
  postTest: []
  maxParallel: 0
  matrix:
    node-10:
      nodeVersion: '10.x'
  additionalVariables: {}

jobs:
  - job: ${{ parameters.name }}
    variables:
      ${{ insert }}: ${{ parameters.additionalVariables }}
    dependsOn:
      - ${{ if parameters.dependsOn }}:
        - ${{ parameters.dependsOn }}
    strategy:
      maxParallel: ${{ parameters.maxParallel }}
      matrix: ${{ parameters.matrix }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    steps:
      - task: UseNode@1
        inputs:
          version: $(nodeVersion)
        displayName: Use Node $(nodeVersion)
      - template: steps/install-deps.yml
      - template: steps/build.yml
        parameters:
          preBuild: ${{ parameters.preBuild }}
          postBuild: ${{ parameters.postBuild }}
      - template: steps/test.yml
        parameters:
          preTest: ${{ parameters.preTest }}
          postTest: ${{ parameters.postTest }}
      - ${{ if eq(parameters.runLint, 'true') }}:
        - template: steps/lint.yml
