parameters:
  name: 'default'
  dependsOn: ''
  vmImage: 'ubuntu-16.04'
  runLint: 'true'
  publishBuildArtifacts: []
  publishTestArtifacts: []
  publishCodeCoverageArtifacts: []
  publishReleaseNotes: 'false'
  publishReleaseNotesArtifact:
    artifactName: 'release-notes'
    targetPath: ''
  maxParallel: 0
  matrix:
    node-10.15.3:
      nodeVersion: '10.15.3'
  additionalVariables: {}

jobs:
  - job: ${{ parameters.name }}
    variables:
      ${{ insert }}: ${{ parameters.additionalVariables }}
    dependsOn:
      - ${{ if parameters.dependsOn }}:
        - ${{ parameters.dependsOn }}
    condition: and(succeeded(), ne(variables.skipJob, 'true'))
    strategy:
      maxParallel: ${{ parameters.maxParallel }}
      matrix: ${{ parameters.matrix }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    steps:
      - task: UseNode@1
        inputs:
          version: $(nodeVersion)
        displayName: Use Node $(nodeVersion)
      - template: steps/install-deps.yml
      - template: steps/set-package-info-variables.yml
      - ${{ if eq(parameters.runLint, 'true') }}:
        - template: steps/lint.yml
      - template: steps/build.yml
      - ${{ each publishBuildArtifact in parameters.publishBuildArtifacts }}:
        - template: steps/publish-build-results.yml
          parameters:
            artifactName: ${{ publishBuildArtifact.artifactName }}
            targetPath: ${{ publishBuildArtifact.targetPath }}
      - template: steps/test.yml
      - ${{ each publishCodeCoverageArtifact in parameters.publishCodeCoverageArtifacts }}:
        - template: steps/publish-code-coverage-results.yml
          parameters:
            summaryFileLocation: ${{ publishCodeCoverageArtifact.summaryFileLocation }}
            reportDirectory: ${{ publishCodeCoverageArtifact.reportDirectory }}
      - ${{ each publishTestArtifact in parameters.publishTestArtifacts }}:
        - template: steps/publish-test-results.yml
          parameters:
            testRunTitle: ${{ publishTestArtifact.testRunTitle }}
            searchFolder: ${{ publishTestArtifact.searchFolder }}
      - ${{ if eq(parameters.publishReleaseNotes, 'true') }}:
        - template: steps/publish-release-notes.yml
          parameters:
            artifactName: ${{ parameters.publishReleaseNotesArtifact.artifactName }}
            targetPath: ${{ parameters.publishReleaseNotesArtifact.targetPath }}
