parameters:
  name: 'default'
  dependsOn: ''
  vmImage: 'ubuntu-16.04'
  runTest: 'true'
  runLint: 'true'
  maxParallel: 3
  matrix:
    node-10:
      nodeVersion: '10.x'

jobs:
  - job: ${{ parameters.name }}
    dependsOn:
      - ${{ if ne(parameters.dependsOn, '') }}:
        - ${{ parameters.dependsOn }}
    strategy:
      maxParallel: ${{ parameters.maxParallel }}
      matrix: ${{ parameters.matrix }}
    pool:
      vmImage: ${{ parameters.vmImage }}
    steps:
      - task: UseNode@1
        inputs:
          version: $(nodeVersion)
        displayName: Use Node $(nodeVersion)
      - template: steps/install-deps.yml
      - template: steps/build.yml
      - template: steps/test.yml
        parameters:
          runTest: ${{ parameters.runTest }}
      - template: steps/lint.yml
        parameters:
          runLint: ${{ parameters.runLint }}
