parameters:
  name: 'multi_platform_build'
  publishBuildArtifacts:
  - publishBuildArtifact:
    artifactName: 'packages'
    targetPath: 'dist/packages'
  publishTestArtifacts:
    - publishTestArtifact:
      testRunTitle: ''
      searchFolder: ''
  publishCodeCoverageArtifacts:
    - publishCodeCoverageArtifact:
      summaryFileLocation: ''
      reportDirectory: ''
  publishReleaseNotesArtifact:
    artifactName: 'release-notes'
    targetPath: ''

stages:
- stage: ${{ parameters.name }}
  jobs:
  - template: build-job.yml
    parameters:
      name: 'default'
      publishBuildArtifacts: ${{ parameters.publishBuildArtifacts }}
      publishTestArtifacts: ${{ parameters.publishTestArtifacts }}
      publishCodeCoverageArtifacts: ${{ parameters.publishCodeCoverageArtifacts }}
      publishReleaseNotesArtifact: ${{ parameters.publishReleaseNotesArtifact }}
      publishReleaseNotes: 'true'
  - template: build-job.yml
    parameters:
      name: 'linux'
      vmImage: 'ubuntu-latest'
      dependsOn: 'default'
      runLint: 'false'
      matrix:
        node-10:
          nodeVersion: '10.x'
        node-12:
          nodeVersion: '12.x'
      additionalVariables:
        skipJob: $[variables.skipLinuxJob]
  - template: build-job.yml
    parameters:
      name: 'macOS'
      vmImage: 'macOS-latest'
      dependsOn: 'default'
      runLint: 'false'
      matrix:
        node-10:
          nodeVersion: '10.x'
        node-12:
          nodeVersion: '12.x'
      additionalVariables:
        skipJob: $[variables.skipMacOSJob]
  - template: build-job.yml
    parameters:
      name: 'windows'
      vmImage: 'windows-latest'
      dependsOn: 'default'
      runLint: 'false'
      matrix:
        node-10:
          nodeVersion: '10.x'
        node-12:
          nodeVersion: '12.x'
      additionalVariables:
        skipJob: $[variables.skipWindowsJob]
