parameters:
  name: 'multi_platform_build'
  # additionalVariables: {}

stages:
- stage: ${{ parameters.name }}
  # variables:
  #   ${{ insert }}: ${{ parameters.additionalVariables }}
  jobs:
  - template: build-job.yml
    parameters:
      name: 'default'
      vmImage: 'ubuntu-16.04'
      publishBuildArtifacts:
        - publishBuildArtifact:
          artifactName: 'packages'
          targetPath: 'dist/packages'
      publishTestArtifacts:
        - publishTestArtifact:
          testRunTitle: 'ng-translit'
          searchFolder: 'dist/junit/ng-translit'
      publishCodeCoverageArtifacts:
        - publishCodeCoverageArtifact:
          summaryFileLocation: 'dist/coverage/ng-translit/cobertura-coverage.xml'
          reportDirectory: 'dist/coverage/ng-translit'
      publishReleaseNotes: 'true'
  - template: build-job.yml
    parameters:
      name: 'linux'
      vmImage: 'ubuntu-latest'
      dependsOn: 'default'
      runLint: 'false'
      matrix:
        node-10:
          nodeVersion: '10.x'
        node-12:
          nodeVersion: '12.x'
      additionalVariables:
        skipJob: $[variables.skipLinuxJob]


  # - ${{ each job in parameters.jobs }}:
  #   - template: build-job.yml
  #     parameters:
  #       name: ${{ job.key }}
  #       ${{ insert }}: ${{ job.value }}
