parameters:
  name: 'multi_platform_build'
  publishBuildArtifacts: []
  publishTestArtifacts: []
  publishCodeCoverageArtifacts: []

stages:
- stage: ${{ parameters.name }}
  jobs:
  - template: build-job.yml
    parameters:
      name: 'default'
      publishBuildArtifacts:
        - ${{ parameters.publishBuildArtifacts }}
      publishTestArtifacts:
        - ${{ parameters.publishTestArtifacts }}
      publishCodeCoverageArtifacts:
        - ${{ parameters.publishCodeCoverageArtifacts }}
      publishReleaseNotes: 'true'
  - template: build-job.yml
    parameters:
      name: 'linux'
      vmImage: 'ubuntu-latest'
      dependsOn: 'default'
      runLint: 'false'
      matrix:
        node-10:
          nodeVersion: '10.x'
        node-12:
          nodeVersion: '12.x'
      additionalVariables:
        skipJob: $[variables.skipLinuxJob]
