parameters:
  name: 'multi_platform_build'
  skipLinuxJob: 'false'
  skipMacOSJob: 'false'
  skipWindowsJob: 'false'
  # additionalVariables: {}

stages:
- stage: ${{ parameters.name }}
  # variables:
  #   ${{ insert }}: ${{ parameters.additionalVariables }}
  jobs:
  - template: build-job.yml
    parameters:
      name: 'default'
      vmImage: 'ubuntu-16.04'
      publishBuildArtifacts:
        - publishBuildArtifact:
          artifactName: 'packages'
          targetPath: 'dist/packages'
      publishTestArtifacts:
        - publishTestArtifact:
          testRunTitle: 'ng-translit'
          searchFolder: 'dist/junit/ng-translit'
      publishCodeCoverageArtifacts:
        - publishCodeCoverageArtifact:
          summaryFileLocation: 'dist/coverage/ng-translit/cobertura-coverage.xml'
          reportDirectory: 'dist/coverage/ng-translit'
      publishReleaseNotes: 'true'
  - ${{ if ne(parameters.skipLinuxJob, 'true') }}:
    - template: build-job.yml
      parameters:
        name: 'linux'
        vmImage: 'ubuntu-latest'
        dependsOn: 'default'
        runLint: 'false'
        matrix:
          node-10:
            nodeVersion: '10.x'
          node-12:
            nodeVersion: '12.x'
  # - ${{ if ne(parameters.skipMacOSJob, 'true') }}:
  #   - template: build-job.yml
  #     parameters:
  #       name: 'macOS'
  #       vmImage: 'macOS-latest'
  #       dependsOn: 'default'
  #       runLint: 'false'
  #       matrix:
  #         node-10:
  #           nodeVersion: '10.x'
  #         node-12:
  #           nodeVersion: '12.x'
  # - ${{ if ne(parameters.skipWindowsJob, 'true') }}:
  #   - template: build-job.yml
  #     parameters:
  #       name: 'windows'
  #       vmImage: 'windows-latest'
  #       dependsOn: 'default'
  #       runLint: 'false'
  #       matrix:
  #         node-10:
  #           nodeVersion: '10.x'
  #         node-12:
  #           nodeVersion: '12.x'

  # - ${{ each job in parameters.jobs }}:
  #   - template: build-job.yml
  #     parameters:
  #       name: ${{ job.key }}
  #       ${{ insert }}: ${{ job.value }}
