parameters:
  name: 'multi_platform_build_test'
  jobs:
    linux:
      parameters:
        name: 'linux'
        vmImage: 'ubuntu-latest'
    macOS:
      parameters:
        name: 'macOS'
        vmImage: 'macOS-latest'
        runLint: 'false'
    windows:
      parameters:
        name: 'windows'
        vmImage: 'windows-latest'
        runLint: 'false'
  additionalVariables: {}

stages:
- stage: ${{ parameters.name }}
  variables:
    ${{ insert }}: ${{ parameters.additionalVariables }}
  jobs:
  - ${{ each job in parameters.jobs }}:
    - template: build-test-job.yml
      parameters:
        ${{ insert }}: ${{ job.parameters }}
