parameters:
  name: 'multi_platform_build'
  publishBuildArtifacts: 'true'
  publishTestArtifacts: 'true'
  publishCodeCoverageArtifacts: 'true'
  publishReleaseNotes: 'true'

stages:
- stage: ${{ parameters.name }}
  jobs:
  - template: build-job.yml
    parameters:
      name: 'default'
      runLint: 'true'
      publishBuildArtifacts: ${{ parameters.publishBuildArtifacts }}
      publishTestArtifacts: ${{ parameters.publishTestArtifacts }}
      publishCodeCoverageArtifacts: ${{ parameters.publishCodeCoverageArtifacts }}
      publishReleaseNotes: ${{ parameters.publishReleaseNotes }}
      additionalVariables:
        nodeVersion: '10.15.3'
  - template: build-job.yml
    parameters:
      name: 'linux'
      vmImage: 'ubuntu-latest'
      dependsOn: 'default'
      runLint: 'false'
      publishBuildArtifacts: 'false'
      publishTestArtifacts: 'false'
      publishCodeCoverageArtifacts: 'false'
      publishReleaseNotes: 'false'
      maxParallel: 2
      matrix:
        node-10:
          nodeVersion: '10.x'
        node-12:
          nodeVersion: '12.x'
      additionalVariables:
        skipJob: $[variables.skipLinuxJob]
  - template: build-job.yml
    parameters:
      name: 'macOS'
      vmImage: 'macOS-latest'
      dependsOn: 'default'
      runLint: 'false'
      publishBuildArtifacts: 'false'
      publishTestArtifacts: 'false'
      publishCodeCoverageArtifacts: 'false'
      publishReleaseNotes: 'false'
      maxParallel: 2
      matrix:
        node-10:
          nodeVersion: '10.x'
        node-12:
          nodeVersion: '12.x'
      additionalVariables:
        skipJob: $[variables.skipMacOSJob]
  - template: build-job.yml
    parameters:
      name: 'windows'
      vmImage: 'windows-latest'
      dependsOn: 'default'
      runLint: 'false'
      publishBuildArtifacts: 'false'
      publishTestArtifacts: 'false'
      publishCodeCoverageArtifacts: 'false'
      publishReleaseNotes: 'false'
      maxParallel: 2
      matrix:
        node-10:
          nodeVersion: '10.x'
        node-12:
          nodeVersion: '12.x'
      additionalVariables:
        skipJob: $[variables.skipWindowsJob]
